---
name: Docker Image
description: Creates a Docker Container Image

inputs:
  token:
    description: Github token
    required: true
    
runs:
  using: composite
  steps:
    - name: Generate version from git
      id: version
      shell: bash
      run: |
        if [ "${{ github.ref_type }}" = "tag" ]; then
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        elif [ "${{ github.ref_name }}" = "main" ]; then
          echo "version=latest" >> $GITHUB_OUTPUT
        else
          echo "version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        fi

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push with Bake
      if: github.event_name != 'pull_request'
      uses: docker/bake-action@v6
      env:
        BUILD_DATE: ${{ github.event.head_commit.timestamp }}
        REGISTRY_IMAGE: ghcr.io/${{ github.repository }}
        SOURCE_COMMIT: ${{ github.sha }}
        VERSION: ${{ steps.version.outputs.version }}
      with:
        targets: image-automated
        push: ${{ fromJSON(inputs.push) }}