---
name: On Merge

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/**'
      - '.github/actions/**'
      - 'Dockerfile*'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Tests
        uses: ./.github/actions/tests

  release-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Latest Image
        uses: ./.github/actions/docker
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: true
          push: true
          tag-strategy: "latest"
        # Ensure context is correct for composite action
        # If build fails, check working-directory or context in action.yml