---
name: On Branch Push

on:
  push:
    branches:
      - '**'
      - '!main'
      - '!renovate/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Tests
        uses: ./.github/actions/tests