---
name: On Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:        
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Tests
        uses: ./.github/actions/tests