---
name: Versioned Release

on:
  push:
    tags:
      - v*

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Tests
        uses: ./.github/actions/tests

  release-image:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Tagged Image
        uses: ./.github/actions/docker
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: false
          push: true
          tag-strategy: "semver"

  release-binaries:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Release Binaries
        uses: ./.github/actions/go-release
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"